### PR TITLE
Style Update on New Version of Slack

### PR DESCRIPTION
**Pull request by zengshengliu**
- Update thread input box color
- Update attachment button color
- Update Ccode snippet background color
- Update broadcast warning popup background

### CODE REVIEW

**Review by mastermel — APPROVED** [review]

**Comment by zengshengliu** [comment]
@mastermel 	Do you know if the automated process to build (`make`) the CSS is still working?  I don't see the CSS file being updated for a while now.

**Comment by mastermel** [comment]
I don't think an automated build has functioned for some time. I generally ping @laCour to do a new build. I'll do that again today...

**Comment by DuBistKomisch** [comment]
I mean if it's just a matter of running `make`, can we not do it ourselves? happy to submit a PR myself if so

**Comment by DuBistKomisch** [comment]
ah I suppose you mean laCour also updates the userstyles.org versions, never mind then

**Pull request merged**
