### PR TITLE
More Style Updates

### PR DESCRIPTION
**Pull request by zengshengliu**
### Channel Header
- Update subtitle color

Before|After
-----|-----
image|image

### Right Header
- Update search box clear button color

Before|After
-----|-----
image|image

- Update search box hover state color

Before|After
-----|-----
image|image

- Update header button color (both normal and hover state)
- Make all buttons on header consistent with color on normal state

Before|After
-----|-----
image|image
image|image
image|image

### App Space
- Update profile side link color

Before|After
-----|-----
image|image
image|image

- Reorganized CSS on `modals/_apps.scss` file

### Footer
- Update context bar color (popup box above input)

Before|After
-----|-----
image|image

### Message Pane
- Update new messages color to be more visible

Before|After
-----|-----
image|image

- Update Primary and Danger button background color

Before|After
-----|-----
image|image
image|image

### Unreads
- Update header color

Before|After
-----|-----
image|image

### Channel Create Modal
- Update channel create modal style

Before|After
-----|-----
image|image

### Channel Preview
- Update channel preview banner notification color

Before|After
-----|-----
image|image

## Preference Page
- Update Do Not Disturb select box colors (disabled state)

Before|After
-----|-----
image|image

- Update select box icon hover state color

Before|After
-----|-----
image|image

## Scrollbar
- Update scrollbar color on newer version

Before|After
-----|-----
image|image

### Activity
- Update Activity View first row line color

Before|After
-----|-----
image|image

- Update message footer channel color

Before|After
-----|-----
image|image

### Keyboard Shortcut
- Update header color

Before|After
-----|-----
image|image

### Workspace Directory (Member Directory)
- Update directory list background color (normal and hover state)

Before|After
-----|-----
image|image
image|image

- Search Bar Icon color (normal and hover state)

Before|After
-----|-----
image|image
image|image

### General
- pillow container hover color

Before|After
-----|-----
image|image

- pillow bottom border color

Before|After
-----|-----
image|image

- Action button color

Before|After
-----|-----
image|image

### Activity View Options
- Update Activity View Options modal color

Before|After
-----|-----
image|image

## Scrollbar
- Update scrollbar color (`c-scrollbar`)

Before|After
-----|-----
image|image

### CODE REVIEW

**Comment by tgburgin** [comment]
@zengshengliu Are you able to provide an updated final CSS file? I don't seem to be able to get the output built.

**Comment by zengshengliu** [comment]
@tgburgin Sorry I just saw your message.  Are you using the default black.css file?

**Comment by zengshengliu** [comment]
@tgburgin Here is the output of the raw folder which contains all CSS variants
[raw.zip](https://github.com/laCour/slack-night-mode/files/3708187/raw.zip)

**Comment by zengshengliu** [comment]
Looks like Slack (at least for the Mac client) released a dark mode.

**Comment by zengshengliu** [comment]
And looks like the theme rollout is across all environments.  I confirmed the web app, windows, and mac all have dark theme available now.

**Pull request closed without merging**
