### PR TITLE
Add styles for thread overview

### PR DESCRIPTION
**Pull request by adeebahmed**
Added styles from https://github.com/laCour/slack-night-mode/issues/218 and a few others to black.css

### CODE REVIEW

**Comment by krazyito65** [comment]
Thank you for this fix until it gets merged in :)

**Comment by ghost** [comment]
Thanks for the fix. Volunteer to help as a maintainer and you can merge it yourself -> https://github.com/laCour/slack-night-mode/issues/229

**Comment by ghost** [comment]
[Contributing guide](https://github.com/laCour/slack-night-mode/blob/master/CONTRIBUTING.md)
Do not make change to any file within the css directory, since these are generated files!!
Changes in css directories won't be merged.

**Comment by mastermel** [comment]
Closing this pull request as I recently made a commit that corrects the styling within our .scss files. As playBraden pointed out, please submit future PRs with changes to only the .scss files an not the .css files :)

**Pull request closed without merging**
