### PR TITLE
Resolve #218, Add One Monokai Darker theme

### LINKED ISSUE #218: The "All Threads" view is not styled and garishly white.
I've collected some custom styles in order to combat this, which makes it look less bad overall, but still needs improving.

```css
.p-threads_view {
  background: #222;
}

.p-threads_view__divider_line {
  border-color: #111;
}

.p-threads_view__divider_label {
  background: #111;
}

.p-threads_view_header__channel_name {
  color: #c7c7c7;
}

.p-threads_view_root {
  border-color: #444;
}

.p-threads_view_reply {
  border-color: #444;
}

.p_threads_view_load_newer_button,
.p_threads_view_load_older_button {
  background: rgba(255, 255, 255, 0.05);
  border-color: #444;
}

.p-threads_view__footer {
  border-color: #444;
}

.p-threads_view__default_background {
  background: rgba(255, 255, 255, 0.05);
}
```

Before:
Screenshot 2019-03-15 at 17 28 59

After:
Screenshot 2019-03-15 at 17 30 46

### PR DESCRIPTION
**Pull request by brandonreid**

### CODE REVIEW

**Comment by tplk** [comment]
Maybe it'd be better to split the fix and addition of the new theme into two separate PRs?

**Comment by mastermel** [comment]
Please only commit changes to files in the scss/ directory. For more information please see the [contributing guide](https://github.com/laCour/slack-night-mode/blob/master/CONTRIBUTING.md). Thanks! :)

**Comment by tplk** [comment]
@mastermel shouldn't you rebuild css from sources before commiting?
I think that's what has been done here.

**Comment by mastermel** [comment]
I believe @laCour set up this project with the intention that the `css/` files be built and committed by just a few people in order to prevent conflicts. So far I think he's the only one that's done that after new changes have been merged for the `scss/` directory. I could be mistaken though 😊 

You'll notice this current PR is now conflicted with master because of this exact thing. Also, this part of the contributing guide is what I'm basing off of: https://github.com/laCour/slack-night-mode/blob/master/CONTRIBUTING.md#syncing-with-upstream

**Comment by vfede** [comment]
#218 is now fixed by https://github.com/laCour/slack-night-mode/commit/515cdc37b3ce7c81d12bca795711077036e1f035

**Pull request closed without merging**
