### PR TITLE
More Style Updates for Latest Slack Version

### PR DESCRIPTION
**Pull request by zengshengliu**
- Update autocomplete pop up window style for action (`/`) and emoji (`:x:`)
- Update download pane
  - Update background color
  - Update close button color
- Update channel topic edit button color
- Update message link color
- Update mention color (use font color (`base-font-color`) as background, background color (`color-shade-darker`) for font color (flip of normal style) and organize in one place
- Update shared post author name color
- Update app textarea popup color
- Update menu description text color
- Update pinned items card color
- Update App Page
  - Update app search input box text color
  - Update app link icon color
  - Update "About this app" description text color
- Update team menu Subtitle color
- Update Preference Page
  - Update close button active state color
  - Update example chat background color
  - Update select option background and font color
- Update profile button color
- Update status text color

### CODE REVIEW

**Comment by Gargaj** [comment]
Could you also look into updating the color of the original poster's name on a shared message?
image

**Comment by zengshengliu** [comment]
@Gargaj 	Done 😄

**Comment by Gargaj** [comment]
Any plans to fix the preferences too? (https://github.com/laCour/slack-night-mode/issues/240)
image

**Comment by zengshengliu** [comment]
@Gargaj 	Preferences is working for me.  Did you build the CSS file yourself? Because the one on the repo hasn't been updated for a while
image

**Review by mastermel — APPROVED** [review]

**Comment by mastermel** [comment]
Thank you for the continued contributions @zengshengliu!

**Pull request merged**
