### PR TITLE
Update Missing Theme Styling

### PR DESCRIPTION
**Pull request by zengshengliu**
Channel Insights Styling
- Change from `c-channel_insights*` to `p-channel_insights*`
- Reorganize channel insights SCSS

Downloads Panel Styling
- Update hint text and background color (App Version)
- Update download action text and background color (App Version)
- Update c-file `Click to download` text and background color

File Upload Dialog
- Update preview image background color and border (copy paste images)
- Unable to locate the selector for the filename character length count box so that part is not themed (file upload from computer)

Message Edit
- Update message update input background and text color
- Update message update confirm and cancel button

Remove a Small White Boarder Under Channel Header

### CODE REVIEW

**Comment by waynehoover** [comment]
Thank you for this, I have been using this branch for the past week and it looks great. Hopefully it gets merged.

**Comment by mastermel** [comment]
@zengshengliu awesome work and thank you so much for helping make this better!

I hate to reject the PR as is, given how much work you've put into it, but [our strategy for this repo](https://github.com/laCour/slack-night-mode/blob/master/CONTRIBUTING.md#making-changes) is to make all changes inside the ./scss directory as it's the source of truth for the repo. The *.css files are auto-generated when we do a release and your changes would simply be overwritten when we do the next one.

If you could revert what you've done to the files under ./css and instead make the relevant edits inside our scss I'd be happy to help get this merged!

**Comment by zengshengliu** [comment]
@mastermel The css files are generated using `make`.  I only make changes on the scss files and then run the make command to generate the css file so that you don't need another commit to do so.  Should I still reverse the change on those generated files?

**Comment by waynehoover** [comment]
@zengshengliu, @mastermel mentioned on my PR https://github.com/laCour/slack-night-mode/pull/196 that they auto generate the CSS in a build step. So to get this merged I believe you must remove the CSS edits and have the PR only be on the .SCSS files.

**Comment by zengshengliu** [comment]
@waynehoover @mastermel Updated.

**Comment by laCour** [comment]
I'll get to releasing this tomorrow. Thanks so much for the high quality PR! :+1:

**Pull request merged**
