### PR TITLE
dark theme for that annoying message on the top 

### PR DESCRIPTION
**Pull request by jkremser**
(message on the top saying: There's more …to the conversation in #{channel})

before: https://i.imgur.com/YAaOswi.png
after: https://i.imgur.com/ADBrJdn.png

### CODE REVIEW

**Comment by jkremser** [comment]
it's been 2 months. Are you interested in the change?

**Comment by mastermel** [comment]
@Jiri-Kremser this looks like a great fix, however you'll need to make your changes to the appropriate spot under the 'scss' directory instead of editing the ./css/raw/black.css file directly. That file is auto-generated when building a new release of the theme.

See the [guide on contributing changes](https://github.com/laCour/slack-night-mode/blob/master/CONTRIBUTING.md#making-changes) for more information!

**Comment by jkremser** [comment]
@mastermel it should be done

**Comment by laCour** [comment]
@Jiri-Kremser Merged and released. Thank you!

**Pull request merged**
