### PR TITLE
Style thread input box

### LINKED ISSUE #180: Thread text field is white
The text field in the thread view no longer matches the rest of the theme:

image

I believe this started happening after Slack updated to allow images in threads.

### PR DESCRIPTION
**Pull request by mortenlj**
This should fix #180 I think. There are more issues in the thread view, but this is the most pressing one for me.

### CODE REVIEW

**Comment by nmielnik** [comment]
This fixes the background color of the textbox, but the bottom still remains with a white background:

screen shot 2018-08-15 at 12 45 35 am


Using this selector fixes the bg color of both the button and the textbox.  There's likely a more elegant fix than this selector, but I figure sharing what I had might inspire an improvement:

```css
#reply_container .inline_message_input_container.with_file_upload {
    background: padding-box #545454;
    border-color: #424242;
    color: #e6e6e6;
}
```

result with this selector:

screen shot 2018-08-15 at 12 46 02 am

**Review by mastermel — CHANGES_REQUESTED** [review]
Thanks for submitting some fixes @mortenlj! However, please don't commit changes to files under ./css, only those under ./scss

**Comment by mortenlj** [comment]
> Thanks for submitting some fixes @mortenlj! However, please don't commit changes to files under ./css, only those under ./scss

Easily fixed. Dropped the css changes now.

**Comment by CrajyB** [comment]
@mastermel It would seem that @mortenlj made the changes you suggested. Could we get this merged into master please?

It would be much appreciated!

**Comment by mortenlj** [comment]
@mastermel or anyone else for that matter. Any chance this could get merged soon? Anything else that needs fixing?

**Comment by stamminator** [comment]
eager spongebob

**Comment by mastermel** [comment]
Sorry for getting back to this so late!

**Comment by AndreasBackx** [comment]
@mastermel no problem, thank you for merging!

**Pull request merged**
