### PR TITLE
Fixed for Slack update 4.0.0

### LINKED ISSUE #235: header and input styles are broken by new July 2019 slack update
here is a gist with my quick fixes 

https://gist.github.com/micahstubbs/e750e5bb8b6adb7b51a961e57660f710

### PR DESCRIPTION
**Pull request by NeQuissimus**
Fixes taken from
https://gist.github.com/micahstubbs/e750e5bb8b6adb7b51a961e57660f710
Fixes #235

All credit goes to @micahstubbs, this is just wrapping their code in a PR

### CODE REVIEW

**Comment by NeQuissimus** [comment]
Note that I could not determine an organizational scheme in the CSS file and hence just pasted :D

**Comment by mastermel** [comment]
Thanks for submitting the PR @NeQuissimus! For this project we actually just make changes to the files in the ./scss/ directory and then autogenerate all of the .css files. If you'd like to update this PR to make the relevant changes to the scss files and reset what you have for the css we could take a look at it!

For more info, see our [contributing guide](https://github.com/laCour/slack-night-mode/blob/master/CONTRIBUTING.md)

**Comment by NeQuissimus** [comment]
On it, my bad.

**Comment by mastermel** [comment]
Also, I just pushed a few fixes myself. Make sure you rebase on master before making your changes :)

**Review by mastermel — CHANGES_REQUESTED** [review]
The scss changes look good, but we're going to have problems if you commit your changes to the ./css/ files. Could you revert those *.css files in your PR and then we can commit the rest?

**Comment by NeQuissimus** [comment]
I dropped the CSS generation

**Comment by micahstubbs** [comment]
thanks for picking this up @NeQuissimus 🙏 🙌

**Review by micahstubbs — APPROVED** [review]
LGTM, as just another community member 😄

**Review by mastermel — APPROVED** [review]

**Pull request merged**
